---
title: "Random Number Generation"
author: "Kun Huang"
date: "`r format(Sys.Date())`"
output: bookdown::html_document2
bibliography: template.bib
biblio-style: asa

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

We consider computational algorithms generating random numbers. These algorithms can produce long sequences of apparently random results, which are in fact completely determined by a shorter initial value, known as a seed value or key. As a result, the entire seemingly random sequence can be reproduced if the seed value is known. This type of random number generator is often called a pseudorandom number generator(PRNG)[(wiki)](https://en.wikipedia.org/wiki/Random_number_generation#%22True%22_vs._pseudo-random_numbers).

Suppose we have attained $U(0,1)$. 

# Inverse CDF

For a continuous distribution function $F$, we can generate a series of random numbers distributed as $F$ by $X=F^{-1}(u),u\sim U(0,1)$
\begin{align}
P(X\leq x) &= P(F^{-1}(u)\leq x)\\
&= P(u\leq F(x))\\
&= F(x)
(\#eq:invCDFc)
\end{align}

However, when $F$ is discrete, we do not have $F^{-1}$. For this situation, we can define the generalized inverse of $F$ as 
\begin{equation}
F^{-}(u) = \inf{x: F(x)\geq u}
(\#eq:gF)
\end{equation}

Then, similar as \@ref(eq:invCDFc), we can generate a random number distributed as $F$ by $X=F^{-}(u),u\sim U(0,1)$.

When $F^{-1}$ is not explicitly known, computing $F^{-1}(u)$ is equivalent to finding a root $x$ of the equation
\begin{equation}
F(x) - u = 0
\end{equation}
Then we can get $F^{-1}(u)$ numerically.

# Rejection Sampling

Suppose our target density $f$ is known up to a constant coefficient $C$, i.e.
\begin{equation}
f(x) = Cq(x)
\end{equation}

Of course we can calculate $C=\frac{1}{\int_\mathcal{X} q(x)dx}$. However, computing $\int_{\mathcal{X}} q(x)dx$ can sometimes be expensive or difficult. *Rejection sampling* can help us with this problem. The idea is, instead of sampling from $f$ directly, we sample from another "instrumental" density $g$ on the same support $\mathcal{X}$ and compare to some criterion to see if this sample is also from $f$. 

Suppose $\exists \alpha, s.t.$, 
\begin{equation}
q(x) \leq \alpha g(x), \forall x \in \mathcal{X}
(\#eq:ratio1)
\end{equation}
$\alpha g(x)$ is called an envelope. Then the rejection sampling can be summarized as 

---

**(Rejection Sampling)**

1. Sample $X\sim g$ and $U\sim \text{Unif(0,1)}$

2. If $U>\frac{q(X)}{\alpha g(X)}$, then go to step 1; else return $X$

---

Intuitively, it works because the ratio $\frac{q(X)}{\alpha g(X)}$ can be considered as the parts that $q(X)$ and $\alpha g(X)$ overlay. Thus the ratio should be close to one ideally. 

Suppose $Y$ is the sampled value, to show $Y$ has density $f$, it suffices to show that $\forall A\subset \mathcal{X}$, 
\begin{equation}
Pr(Y\in A) = \int_{A} f(x) dx
(\#eq:rejproof)
\end{equation}

From the procedure, let $Xg$ be the sampled value from $g$, notice that $Pr(U\leq \frac{q(X)}{\alpha g(X)}) = \frac{q(X)}{\alpha g(X)}$, we have 

\begin{align}
Pr(Y\in A) & = \frac{Pr(Xg\in A,Xg \text{ is accepted})}{Pr(Xg\text{ is accepted})}\\
&= \frac{Pr(Xg\in A,Xg \text{ is accepted}, Xg \text{ is from } g)}{Pr(Xg\text{ is accepted})}\\
&= \frac{\int_{A} \frac{q(X)}{\alpha g(X)} g(x)dx}{\alpha^{-1}\int q(x)dx}\\
&= \int_{A} f(x)dx
\end{align}

When $f(x)\propto\sum_{k=1}^m q_{k}(x)$, if we have a series of density $g_1,...,g_m, s.t.$
\begin{equation*}
q_k(x)\leq \alpha_k g_k(x), \forall x\in \mathcal{X}
\end{equation*}
we have similar result.

---

**(Rejection Sampling)**

1. Sample $k$ from $\{1,...,m\}$ with probability $p_k\propto\alpha_k$

2. Sample $X\sim g_k$ and $U\sim \text{Unif(0,1)}$

3. If $U>\frac{q_k(X)}{\alpha_k g_k(X)}$, then go to step 1; else return $X$

---

# Sampling using Markov Chains

## Background of Markov Chains

Let $\mathcal{X}$ be a discrete of Euclidean space, a stochastic process $\{X_t, t=0,1,...\}, X_t\in\mathcal{X}$ is called *Markov chain* if 
\begin{equation}
P(X_t\in A|X_{t-1},...,X_1,X_0) \stackrel{a.s.}{=} P(X_t\in A|X_{t-1}), \forall t>0, \ \forall A\subset\mathcal{X}
(\#eq:MC)
\end{equation}
Thus the state at $T=t$ only depends on the previous state. The marginal distribution of $X_0$ is called the initial distribution of the Markov chain $(X_t)$. Moreover, if the conditional density of any two consecutive states are the same, i.e. $\forall a,b$
\begin{equation}
p(x_t=b|x_{t-1}=a):=q(b|a), \forall t>0
(\#eq:HMC)
\end{equation}
are the same, then the chain is called *homogeneous*, $q(\cdot|\cdot)$ is called the *transition kernel* of the Markov chain.

For a homogeneous Markov chain $(X_t)$, if $X_0\sim\pi,s.t.$
\begin{equation}
\pi(x) = \int q(x|y)\pi(y)dy
(\#eq:initpi)
\end{equation}
Then the density $p_t$ of $X_t$ can be written as 
\begin{align}
p_t(x) &= \int q(x|y)p_{t-1}(y)dy\\
&\stackrel{\text{homogeneous}}{=}\int q(x_{1}=x|x_{0}=y)p_0(y)dy\\
&=\int q(x|y)\pi(y)dy\\
&=\pi(x), \forall t\geq0
(\#eq:stationary)
\end{align}

We introduce the idea of *stationary distribution*, that is, a stationary distribution of a Markov chain is a probability distribution that remains unchanged in the Markov chain as time progresses.
From \@ref(eq:stationary), $\pi$ is the stationary distribution of a homogeneous Markov chain $(X_t)$. For non-homogeneous Markov chains, under certain condistions, there exists an unique stationay distribution whatever the initial distribution $p_0,$ as $t\rightarrow\infty,p_t\rightarrow\pi$. 

We sample the target distribution $f$ based on the existence and uniqueness of the stationary distribution of a Markov chain $(X_t)$. That is, we construct a Markov chain such that its stationary distribution is $f$, then $X_t$ is the random sample asympotic to $f$ when $n$ is large enough. 

The question is **how to choose the transition probability $q(\cdot|\cdot)$ such that $f$ is a stationary distribution of $(X_t)$**.

When $f$ is known up to a multiplicative factor, i.e.
$$
f(x) = \frac{h(x)}{C}, C>0
$$
The *detailed balance condition* \@ref(eq:dbc) answers the above question.
\begin{equation}
h(x)q(y|x) = h(y)q(x|y), \forall x\not=y\in\mathcal{X}
(\#eq:dbc)
\end{equation}
This is because from \@ref(eq:dbc), we have $f(x)q(y|x) = f(y)q(x|y)$, then 
\begin{equation}
p_t(y)=\int f(x)q(y|x) dx = \int f(y)q(x|y) dx = f(y)\underbrace{\int q(x|y) dx}_{=1}
\end{equation}

To determine the transition probability(kernel) $q(\cdot|\cdot)$, we have **Metropolis-Hastings(MH)** algorithm. 

## Metropolis-Hastings(MH) Algorithm

To sample from $f(x) = \frac{h(x)}{C}, C>0$, suppose we have known a *proposal distribution* $k(y|x)$

---

**Metropolis-Hastings(MH) Algorithm**

1. Set $x_0,s.t. h(x_0)>0$
2. For $t=1,2,...,n$
  - Draw $x^*\sim k(\cdot|x_t)$ and $U\sim\text{Unif}(0,1)$,
  
  - Compute the MH ratio $R(x_t,x^*)=\frac{h(x^*)k(x_t|x^*)}{h(x_t)k(x^*|x_t)}$
  
  - If $U\leq\min\{R(x_t,x^*),1\}$, then $x_{t+1}=x^*$, else $x_{t+1} = x_t$
  
---

### Example, Bayesian Inference

We show an example using MH algorithm in Bayesian inference. For a parametric family of probability $f(x|\theta)$, given data $x$ and the prior density $p(\theta)$, the posterior density of $\theta$ is 
\begin{equation}
p(\theta|x) = \frac{f(x|\theta)p(\theta)}{\int f(x|\theta)p(\theta)d\theta} \propto h(\theta)
(\#eq:bayes)
\end{equation}

We can use the prior $p(\theta)$ as a proposal distribution, i.e. $k(\theta^*|\theta_t)=p(\theta^*)$. Then $R(\theta_t,\theta^*)=\frac{h(\theta^*) p(\theta_t)}{h(\theta_t)p(\theta^*)}=\frac{h(\theta^*)}{p(\theta^*)}/\frac{h(\theta_t)}{p(\theta_t)}=\frac{f(x|\theta^*)}{f(x|\theta_t)}$.

## Gibbs Sampling

Gibbs sampling is adapted for multidimensional target distributions by sequentially sampling from the conditional distributions of parts of the random vector. The idea is also used in the coordinate descent algorithm. 


---

**(Gibbs Sampler)**

---

# Acknowledgment {-}

The above contents are notes after taking the class by @stat5361. 

# Reference {-}
